### PR TITLE
Fixed a missing semicolon

### PR DESCRIPTION
**Pull request by 0atman**
Fixed a missing semicolon in the integer section. Easy to miss!

### CODE REVIEW

**Comment by 0atman** [comment]
Thanks @vitiral! To repeat what I said on Twitter: I wonder, `std_prelude` has been broken since 26 Apr 2018, would you like a co-maintainer on the project? I'm really keen on it, and it's slipped behind a bit. Let me know!

**Comment by vitiral** [comment]
sure, I definitely won't pass up help. Are you volunteering?

Sorry, I'm not on twitter (anymore). If what you said was lengthy you can email me vitiral@gmail.com

**Comment by 0atman** [comment]
Sure am, I'll email.

**Comment by 0atman** [comment]
Hi Rett! I really love std_prelude, so I'm absolutely volunteering!

A bit about me: I am familiar with maintaining open-source projects on
github, I'm co-maintainer of https://github.com/inim-repl/INim, though
I've appointed my successor due to my recent transition to Rust. Nim's
great, but Rust is revolutionary.
Speaking of, maybe you've seen one of my Rust videos doing the rounds? A
startling number of people have, to my great surprise!
https://www.youtube.com/playlist?list=PLZaoyhMXgBzoM9bfb5pyUOT3zjnaDdSEP

Want to team up?
Tris

On July 19, 2022, GitHub ***@***.***> wrote:
> sure, I definitely won't pass up help. Are you volunteering?
>
> Sorry, I'm not on twitter (anymore). If what you said was lengthy you
> can email me ***@***.*** ***@***.***>
>

—
Reply to this email directly, view it on GitHub
<https://github.com/vitiral/std_prelude/pull/2#issuecomment-1189468563>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAA33MI3FRAXQHFY7IJA7M3VU36M3ANCNFSM54AQBS2A>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by 0atman** [comment]
lol I just noticed I emailed github, not you directly. I'm an extremely smart developer. Lemme email direct and get the ball rolling, I'd really like to help!

**Comment by vitiral** [comment]
Sorry I missed the email from 2 years ago. LGTM, you're hired.

I haven't used rust in years (doing my own project rewriting the whole techstack at http://civboot.org), current project is create a self-contained development environment in Lua: http://github.com/civboot/civlua

You're free to take total ownership, though I'd still remain as owner of the group for at least a year. SGTY?

**Comment by vitiral** [comment]
Also `std_prelude` would fit quite well into a "no boilerplate" video lol

**Comment by vitiral** [comment]
Ah I just realized this isn't part of https://github.com/rust-crates

The way I'd do this is:

* move this repo into https://github.com/rust-crates
* make you maintainer of https://github.com/rust-crates and controller of Cargo key
* ???
* Profit!

**Comment by vitiral** [comment]
I've done all the above except the Cargo key. I'll push the first changes for a bit, then give you the keys :smile:

**Comment by 0atman** [comment]
Amazing! Sorry, this week was a video week, which I just published! :laughing: 
I'm game! :-)

**Pull request merged**
